name: Phan
description: Analyze a PHP codebase with Phan
author: Albert Peschar
inputs:
  token:
    description: "your GITHUB_TOKEN"
    required: true
runs:
  using: docker
  image: docker://ghcr.io/apeschar/phan-action:latest
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
