name: Phan
description: Analyze a PHP codebase with Phan
author: Albert Peschar
runs:
  using: docker
  image: docker://ghcr.io/apeschar/phan-action:latest
  env:
    GITHUB_TOKEN: ${{ github.token }}
