name: Publish Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "42 2 * * *"

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/apeschar/phan-action:latest
            ghcr.io/apeschar/phan-action:${{ steps.date.outputs.date }}
